### ISSUE TITLE
Pathway 1 timeline

### ISSUE THREAD

**Issue by rmccrear** [CodeXCourses/level-1-course-content#11]
We might discuss the long term scheduling here.

### Breaks

Nov 10 Veteran's Day (Observed) (Fri)
Nov 11 Veteran's Day (Sat)
Nov 23-24 Thanksgiving (Th-Fri)

I'm thinking I ought to give them the weekend for breaks. 
(This would keep us both in sync as well.)
We want to be sustainable of 9 months. And giving time off for family is important.

### Schedule

I will start the "week" on Saturday. That will be Lewis' Monday.
(My Friday will be his Thursday. So we are synced up.)
e.g. Sat Oct 7 is the start of the week of Sat Oct 7 - Fri Oct 13
Just add two days to get to Monday.

#### No break schedule

Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 14 - Week 1: Introduction and In-depth Study of HTML
Oct 21 - Week 2: Cascading Style Sheets (CSS)
Oct 28 - Week 3: Bootstrap Framework
Nov 4 - Week 4: Git, Github, and Deployment
Nov 11 - Week 5: JavaScript Developer 1 (Basic Concepts)
Nov 18 - Week 6: JavaScript Developer 2 (Intermediate Concepts)
Nov 25 - Week 7: Capstone Project

**Comment by rmccrear** [comment]
Here are some alternatives:

### With a break

Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 14 - Week 1: Introduction and In-depth Study of HTML
Oct 21 - Week 2: Cascading Style Sheets (CSS)
Oct 28 - Week 3: Bootstrap Framework
Nov 4 - Week 4: Git, Github, and Deployment
Nov 11 - Week 5: (Veterans Day 1day)JavaScript Developer 1 (Basic Concepts)
Nov 18 - Break
Nov 25 - (Thanksgiving 2days) Week 6: JavaScript Developer 2 (Intermediate Concepts) 
Dec 2 - Week 7: Capstone Project

### No break

But put Git, Github, and Deployment on Thanksgiving week.
This may be rushing it.

Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 14 - Week 1: Introduction and In-depth Study of HTML
Oct 21 - Week 2: Cascading Style Sheets (CSS)
Oct 28 - Week 3: Bootstrap Framework
Nov 4 - Week 4: JavaScript Developer 1 (Basic Concepts)
Nov 11 - Week 5: (Veterans Day 1day) JavaScript Developer 2 (Intermediate Concepts) 
Nov 18 - Week 6: (Thanksgiving 2days) Git, Github, and Deployment 
Nov 25 - Week 7: Capstone Project


or maybe 


Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 14 - Week 1: Introduction and In-depth Study of HTML
Oct 21 - Week 2: Cascading Style Sheets (CSS)
Oct 28 - Week 3: Bootstrap Framework
Nov 4 - Week 4: Veterans Day 1day)JavaScript Developer 1 (Basic Concepts)
Nov 11 -  Break
Nov 18 - Week 5: Git, Github, and Deployment (Start Javascript here, also)
Nov 25 - (Thanksgiving 2days) Week 6: JavaScript Developer 2 (Intermediate Concepts) 
Dec 2 - Week 7: Capstone Project

Or we can double up on Thanksgiving. But they might not work much that week.

Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 14 - Week 1: Introduction and In-depth Study of HTML
Oct 21 - Week 2: Cascading Style Sheets (CSS)
Oct 28 - Week 3: Bootstrap Framework
Nov 4 - Week 4: (Veterans Day 1day) JavaScript Developer 1 (Basic Concepts)
Nov 11 -  Week 5: Git, Github, and Deployment (Review Javascript here, also)
Nov 18 - Break for Thanksgiving week
Nov 25 - Week 6: JavaScript Developer 2 (Intermediate Concepts) 
Dec 2 - Week 7: Capstone Project

**Comment by tm-LBenson** [comment]
(Saturday - Thursday):

Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 14 - Week 1: Introduction and In-depth Study of HTML
Oct 21 - Week 2: Cascading Style Sheets (CSS)
Oct 28 - Week 3: Bootstrap Framework
Nov 4 - Week 4: JavaScript Developer 1 (Basic Concepts)
Nov 11 - Break (Veteran's Day and Post-JS1 consolidation)
Nov 18 - Week 5: Git, Github, and Deployment
Nov 25 - Break for Thanksgiving week
Dec 2 - Week 6: JavaScript Developer 2 (Intermediate Concepts)
Dec 9 - Week 7: Capstone Project

This Gives 2 weeks off during the cohort, without interrupting any holidays, and it puts a break after JS 1. With git and the break, that gives students 2 weeks to work on their JS 1 prior to starting JS 2. 

(Monday - Friday):
(same as above)
Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 16 - Week 1: Introduction and In-depth Study of HTML
Oct 23 - Week 2: Cascading Style Sheets (CSS)
Oct 30 - Week 3: Bootstrap Framework
Nov 6 - Week 4: JavaScript Developer 1 (Basic Concepts)
Nov 13 - Break (Post-JS1 consolidation week)
Nov 20 - Week 5: Git, Github, and Deployment
Nov 27 - Break for Thanksgiving week
Dec 4 - Week 6: JavaScript Developer 2 (Intermediate Concepts)
Dec 11 - Week 7: Capstone Project

**Comment by rmccrear** [comment]
I do like this one.

It doesn't cram the Capstone right around Thanksgiving.

It give a lot of space for learning JS fundamentals, like Objects and Functions. Which went over some people's heads in my class last time.

It also gives a chance to get JS2 into GitHub for portfolios, as you mentioned.

**Comment by tm-LBenson** [comment]
Great! Do you have a plan for displaying this schedule to the students?

**Comment by rmccrear** [comment]
Yes, I will put in on the Google Calendar. I'll see how that looks. 

I'm not sure if Google Classroom has a place for a sylabus or just for "posts".

**Comment by rmccrear** [comment]
(Monday - Friday):
Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 16 - Week 1: Introduction and In-depth Study of HTML
Oct 23 - Week 2: Cascading Style Sheets (CSS)
Oct 30 - Week 3: Bootstrap Framework
Nov 6 - Week 4: JavaScript Developer 1 (Basic Concepts) (Veteran’s Day)
Nov 13 - Week 5: Git, Github, and Deployment
Nov 20 - Week 6: JavaScript Developer 2 (Intermediate Concepts) Break for Thanksgiving--2 days.
Nov 27 - Week 7: JavaScript Developer 2 (Intermediate Concepts)
Dec 4 - Week 7: Capstone Project

**Comment by rmccrear** [comment]
Or, with more breaks.


(Monday - Friday):
Oct 7 - Week 0: Orientation & Introduction to Code Editor and Browser Tools
Oct 16 - Week 1: Introduction and In-depth Study of HTML
Oct 23 - Week 2: Cascading Style Sheets (CSS)
Oct 30 - Week 3: Bootstrap Framework
Nov 6 - Week 4: JavaScript Developer 1 (Basic Concepts) (Veteran’s Day)
Nov 13 - Week 5: Git, Github, and Deployment
Nov 20 - Week 6: Break for Thanksgiving--5 days.
Nov 27 - Week 7: JavaScript Developer 2 (Intermediate Concepts)
Dec 4 - Week 7: Capstone Project

**Comment by tm-LBenson** [comment]
I think we are good on this, so I am going to close this issue
