### ISSUE TITLE
HTML Badge discussion

### ISSUE THREAD

**Issue by rmccrear** [CodeXCourses/level-1-course-content#13]
How will we structure our class? 

Will it be 2 hours lecture, 1 hour workshop?

**Comment by rmccrear** [comment]
One way to structure the class is to follow the topics of one of the videos. For example, we could cover material this 4 hour video from start to end, a few sections a day. Then they can use it to review after class.

https://www.youtube.com/watch?v=kUMe1FH4CHE

**Comment by tm-LBenson** [comment]
My plan is to follow the timeline in the day.md files, then I will do breakout rooms and let the students work on their assignments that will be due. During that time I will move around the class through the breakout rooms to check if they need assistance. This can give them a chance to collaborate a bit.

**Comment by ReeceRenninger** [comment]
I think establishing some time at the end of lecture to go into lab work will be beneficial especially as the concepts get more complex in the later weeks, but its whatever you all feel is best for your style of teaching
